setwd("/home/jacobhsu/ISPP_Paper/Data/Final_score/compare/")
par(mfrow=c(1,3))
AD_onhOMIM <- read.csv("onlu_on_hOMIM_AR_ISPP_AD.csv",header = FALSE)
AR_onhOMIM <- read.csv("onlu_on_hOMIM_AR_ISPP_AR.csv",header = FALSE)
t.test(AD_onhOMIM$V2,AR_onhOMIM$V2)
boxplot(AD_onhOMIM$V2,AR_onhOMIM$V2,main= "hOMIM study ; Wilcoxon rank sum test (p-value = 2.559e-08)", ylab="Inheritance mode specific pathogenic score",names=c("AD score","AR score"))
wilcox.test(AD_onhOMIM$V2,AR_onhOMIM$V2)

AD_onREC <- read.csv("only_on_REC_AR_ISPP_AD.csv",header = FALSE)
AR_onREC <- read.csv("only_on_REC_AR_ISPP_AR.csv",header = FALSE)
t.test(AD_onREC$V2,AR_onREC$V2)
boxplot(AD_onREC$V2,AR_onREC$V2,main= "REC study ; Wilcoxon rank sum test (p-value = 5.441e-06)", ylab="Inheritance mode specific pathogenic score",names=c("AD score","AR score"))
wilcox.test(AD_onREC$V2,AR_onREC$V2)

AD_onGENIC <- read.csv("only_on_RVIS_AR_ISPP_AD.csv",header = FALSE)
AR_onGENIC <- read.csv("only_on_RVIS_AR_ISPP_AR.csv",header = FALSE)
t.test(AD_onGENIC$V2,AR_onGENIC$V2)
boxplot(AD_onGENIC$V2,AR_onGENIC$V2,main= "GENIC study ; Wilcoxon rank sum test (p-value = 3.93e-09)", ylab="Inheritance mode specific pathogenic score",names=c("AD score","AR score"))
wilcox.test(AD_onGENIC$V2,AR_onGENIC$V2)

setwd("/home/jacobhsu/")
tiff("./ISPP_Paper/Figures/S4B_150dpi.tiff", width = 178, height = 70, units = 'mm',pointsize = 5, res = 150)
par(mfrow=c(1,3))
boxplot(AD_onhOMIM$V2,AR_onhOMIM$V2,main= "hOMIM study ; Wilcoxon rank sum test (p = 2.559e-08)", ylab="ISPP score",names=c("ISPP_AD","ISPP_AR"),cex.lab=1.5,cex.axis=1.5)
boxplot(AD_onREC$V2,AR_onREC$V2,main= "REC study ; Wilcoxon rank sum test (p = 5.441e-06)", ylab="ISPP score",names=c("ISPP_AD","ISPP_AR"),cex.lab=1.5,cex.axis=1.5)
boxplot(AD_onGENIC$V2,AR_onGENIC$V2,main= "RVIS study ; Wilcoxon rank sum test (p = 3.93e-09)", ylab="ISPP score",names=c("ISPP_AD","ISPP_AR"),cex.lab=1.5,cex.axis=1.5)
dev.off() 
